name: Build
on: [ push, pull_request ]

jobs:
  build_for_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - name: Build application
        run: yarn run make -p win32
