name: Build
on: [ push, pull_request ]

jobs:
  build_for_windows1:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn run rebuild-sqlite3
      - run: yarn run rebuild
      - run: yarn run win32-make
