name: Build
on: [ push, pull_request ]

jobs:
  build_for_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Install wine
      run: sudo apt install wine -y
      - uses: borales/actions-yarn@v2.3.0
        with:
          cmd: win32-make
