name: Build
on: [ push, pull_request ]

jobs:
  build_for_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine -y
      - name: Add wine to path
        run: export PATH="/usr/bin:$PATH"
      - run: yarn install
      - run: pwd && ls -l
      - run: yarn run win32-make
