name: Release
#on:
#  workflow_run:
#    workflows: [ "Build" ]
#    types:
#      - completed

on: [ push, pull_request ]

jobs:
  publish_on_windows:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: sd
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine -y
      - name: Add wine to path
        run: export PATH="/usr/bin:$PATH"
      - run: yarn install
      - name: Run publish dry run
        run: yarn run publish --dry-run -p win32
      - name: Fix artifacts file
        run: sd ',"[^"]+delta\.nupkg"' '' out/publish-dry-run/*/*
      - name: Publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish --from-dry-run -p win32
      - name: Upload to S3 Bucket
        uses: Noelware/s3-action@1.2.0
        with:
          directories: 'out/make/squirrel.windows/x64'
          access-key: AKIAQWXRPHKDXS3VME3A
          secret-key: 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
          name: companyaddresstrackerpseudo
