name: Release
on: [push, pull_request]

jobs:
  publish_on_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Get package version
        run: echo "PACKAGE_VERSION=$(cat package.json | jq -r '.version')" >> $GITHUB_ENV
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine -y
      - run: yarn install
      - name: Build
        run: yarn run make -p win32
      - name: S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-west-2'
          SOURCE_DIR: 'out/make/squirrel.windows/x64'
          DEST_DIR: RELEASES/win32/${{ env.PACKAGE_VERSION }}
      - name: Adding to update server
        run: 'curl -d "{"version": "${{ env.PACKAGE_VERSION }}", "platform": "win32" }" -H "Content-Type: application/json" -X POST https://aws.loc0ded.com/addRelease'
