name: Release
on: [push, pull_request]

jobs:
  publish_on_windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine -y
      - run: yarn install
      - name: Publish
        run: yarn run publish -p win32
