name: Release
on:
  workflow_run:
    workflows: [ "Release" ]
    types:
      - completed

jobs:
  publish_on_windows:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - name: Install wine
        run: sudo dpkg --add-architecture i386 && sudo apt-get update && sudo apt-get install wine -y
      - name: Add wine to path
        run: export PATH="/usr/bin:$PATH"
      - run: yarn install
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: yarn run publish -p win32
